### ISSUE TITLE
Problemas para compilar el código

### ISSUE THREAD

**Issue by batlupus7** [JavierIH/kame#1]
Buenas Javier, he construido el minikame para raspberry pi 3. He metido tu código de este repositorio junto las librerias adicionales de pybotics. El caso es que cuando ejecuto el main.py me da errores. Son estos:

> Traceback (most recent call last):
>   File "main.py", line 3, in <module>
>     robot = Kame([-5, -14, 4, 20, -10, 0, 12, 5], [3, 2, 15, 12, 1, 0,  14, 13])
>   File "/home/pi/kame/code/kame.py", line 43, in __init__
>     self.controller = ServoController(self._bus, self._pca9685_address)
>   File "/home/pi/kame/code/driver/pca9685/pca9685.py", line 17, in __init__
>     self.setFrequency(self._update_rate)
>   File "/home/pi/kame/code/driver/pca9685/pca9685.py", line 42, in setFrequency
>     self.bus.write_byte_data(self.address, 0x00, 0x10)
> OSError: [Errno 121] Remote I/O error

Si eres tan amable me podrías indicar como proseguir?
Gracias de antemano.

**Comment by JavierIH** [comment]
Hola batlupus7,

Este robot utiliza una placa PCA9685 conectada a la Raspberry para controlar los servos. Creo que el error ocurre por algún problema en la conexión. Prueba a ejecutar este comando para revisar que funciona el bus i2c y que te detecta el PCA9685 cuando lo tengas conectado.

`sudo i2cdetect -y 1`

El programa está utilizando la dirección 0x40 por defecto, si tu placa tuviera una dirección diferente (se configura físicamente con unos jumpers) habría que cambiar la dirección.
